export const BLOOD_GROUPS = [
  'A_POSITIVE',
  'A_NEGATIVE',
  'B_POSITIVE',
  'B_NEGATIVE',
  'AB_POSITIVE',
  'AB_NEGATIVE',
  'O_POSITIVE',
  'O_NEGATIVE',
];

export const COMPONENTS = ['WHOLE_BLOOD', 'RED_CELLS', 'PLASMA', 'PLATELETS'];

export const URGENCY = ['NORMAL', 'URGENT', 'CRITICAL'];

export const REQUEST_STATUS = [
  'MATCHING',
  'PARTIALLY_FULFILLED',
  'FULFILLED',
  'CANCELLED',
];